export const AUTHORIZATION_REQUEST = "AUTHORIZATION_REQUEST";
export const AUTHORIZATION_SUCCESS = "AUTHORIZATION_SUCCESS";
export const AUTHORIZATION_FAILURE = "AUTHORIZATION_FAILURE";

export const UN_AUTHORIZATION = "UN_AUTHORIZATION";
