export const FETCH_USER_MISSIONS_REQUEST = "FETCH_USER_MISSIONS_REQUEST";
export const FETCH_USER_MISSIONS_SUCCESS = "FETCH_USER_MISSIONS_SUCCESS";
export const FETCH_USER_MISSIONS_FAILURE = "FETCH_USER_MISSIONS_FAILURE";

export const FETCH_USER_MARKED_MISSIONS_REQUEST =
  "FETCH_USER_MARKED_MISSIONS_REQUEST";
export const FETCH_USER_MARKED_MISSIONS_SUCCESS =
  "FETCH_USER_MARKED_MISSIONS_SUCCESS";
export const FETCH_USER_MARKED_MISSIONS_FAILURE =
  "FETCH_USER_MARKED_MISSIONS_FAILURE";
