// Local types
export const RESET_MISSIONS_FROM_STORE = "RESET_MISSIONS_FROM_STORE";

export const FILTER_MISSIONS_BY_SEARCHSTRING = "FILTER_MISSIONS_BY_SEARCHSTRING";

export const CHANGE_CURRENT_TABLE_TYPE = "CHANGE_CURRENT_TABLE_TYPE";

// API types

export const FETCH_USER_MISSIONS_REQUEST = "FETCH_USER_MISSIONS_REQUEST";
export const FETCH_USER_MISSIONS_SUCCESS = "FETCH_USER_MISSIONS_SUCCESS";
export const FETCH_USER_MISSIONS_FAILURE = "FETCH_USER_MISSIONS_FAILURE";

export const FETCH_MISSION_DATA_REQUEST = "FETCH_MISSION_DATA_REQUEST";
export const FETCH_MISSION_DATA_SUCCESS = "FETCH_MISSION_DATA_SUCCESS";
export const FETCH_MISSION_DATA_FAILURE = "FETCH_MISSION_DATA_FAILURE";

export const FETCH_MARKED_MISSIONS_REQUEST = "FETCH_MARKED_MISSIONS_REQUEST";
export const FETCH_MARKED_MISSIONS_SUCCESS = "FETCH_MARKED_MISSIONS_SUCCESS";
export const FETCH_MARKED_MISSIONS_FAILURE = "FETCH_MARKED_MISSIONS_FAILURE";

export const FETCH_MISSIONS_BY_SEARCHSTRING_REQUEST =
  "FETCH_MISSIONS_BY_SEARCHSTRING_REQUEST";
export const FETCH_MISSIONS_BY_SEARCHSTRING_SUCCESS =
  "FETCH_MISSIONS_BY_SEARCHSTRING_SUCCESS";
export const FETCH_MISSIONS_BY_SEARCHSTRING_FAILURE =
  "FETCH_MISSIONS_BY_SEARCHSTRING_FAILURE";

export const MARK_MISSION_REQUEST = "MARK_MISSION_REQUEST";
export const MARK_MISSION_SUCCESS = "MARK_MISSION_SUCCESS";
export const MARK_MISSION_FAILURE = "MARK_MISSION_FAILURE";

export const UNMARK_MISSION_REQUEST = "UNMARK_MISSION_REQUEST";
export const UNMARK_MISSION_SUCCESS = "UNMARK_MISSION_SUCCESS";
export const UNMARK_MISSION_FAILURE = "UNMARK_MISSION_FAILURE";

export const REMOVE_MISSION_MEMBERSHIP_REQUEST =
  "REMOVE_MISSION_MEMBERSHIP_REQUEST";
export const REMOVE_MISSION_MEMBERSHIP_SUCCESS =
  "REMOVE_MISSION_MEMBERSHIP_SUCCESS";
export const REMOVE_MISSION_MEMBERSHIP_FAILURE =
  "REMOVE_MISSION_MEMBERSHIP_FAILURE";

export const ADD_MISSION_MEMBERSHIP_REQUEST = "ADD_MISSION_MEMBERSHIP_REQUEST";
export const ADD_MISSION_MEMBERSHIP_SUCCESS = "ADD_MISSION_MEMBERSHIP_SUCCESS";
export const ADD_MISSION_MEMBERSHIP_FAILURE = "ADD_MISSION_MEMBERSHIP_FAILURE";

export const FETCH_MISSION_REQUEST = "FETCH_MISSION_REQUEST";
export const FETCH_MISSION_SUCCESS = "FETCH_MISSION_SUCCESS";
export const FETCH_MISSION_FAILURE = "FETCH_MISSION_FAILURE";
