// Local TYPES

export const ADD_REGISTRY_TO_STORE = "ADD_REGISTRY_TO_STORE";
export const ADD_TEMPLATE_REGISTRY_TO_STORE = "ADD_TEMPLATE_REGISTRY_TO_STORE";

export const REMOVE_NEW_REGISTRY_FROM_STORE = "REMOVE_NEW_REGISTRY_FROM_STORE";
export const REMOVE_REGISTRY_FROM_STORE = "REMOVE_REGISTRY_FROM_STORE";
export const REMOVE_TEMPLATE_REGISTRIES_FROM_STORE =
  "REMOVE_TEMPLATE_REGISTRIES_FROM_STORE";

export const UPDATE_NEW_REGISTRY_FROM_STORE = "UPDATE_NEW_REGISTRY_FROM_STORE";
export const UPDATE_OLD_REGISTRY_FROM_STORE = "UPDATE_OLD_REGISTRY_FROM_STORE";

export const COMMIT_REGISTRY_FROM_TEMPLATE_TO_STORE =
  "COMMIT_REGISTRY_FROM_TEMPLATE_TO_STORE";

export const RESET_IS_SUCCESFULLY_SAVED_FROM_STORE = "RESET_IS_SUCCESFULLY_SAVED_FROM_STORE";

// API TYPES

export const FETCH_TIME_REPORT_DATA_REQUEST = "FETCH_TIME_REPORT_DATA_REQUEST";
export const FETCH_TIME_REPORT_DATA_SUCCESS = "FETCH_TIME_REPORT_DATA_SUCCESS";
export const FETCH_TIME_REPORT_DATA_FAILURE = "FETCH_TIME_REPORT_DATA_FAILURE";

export const FETCH_REGISTRIES_BY_WEEK_REQUEST = "FETCH_REGISTRIES_BY_WEEK_REQUEST";
export const FETCH_REGISTRIES_BY_WEEK_SUCCESS = "FETCH_REGISTRIES_BY_WEEK_SUCCESS";
export const FETCH_REGISTRIES_BY_WEEK_FAILURE = "FETCH_REGISTRIES_BY_WEEK_FAILURE";

export const FETCH_TIME_REPORT_DAY_DATA_REQUEST = "FETCH_TIME_REPORT_DAY_DATA_REQUEST";
export const FETCH_TIME_REPORT_DAY_DATA_SUCCESS = "FETCH_TIME_REPORT_DAY_DATA_SUCCESS";
export const FETCH_TIME_REPORT_DAY_DATA_FAILURE = "FETCH_TIME_REPORT_DAY_DATA_FAILURE";

export const FETCH_REGISTRIES_BY_DAY_REQUEST = "FETCH_REGISTRIES_BY_DAY_REQUEST";
export const FETCH_REGISTRIES_BY_DAY_SUCCESS = "FETCH_REGISTRIES_BY_DAY_SUCCESS";
export const FETCH_REGISTRIES_BY_DAY_FAILURE = "FETCH_REGISTRIES_BY_DAY_FAILURE";

export const SAVE_CHANGES_REQUEST = "SAVE_CHANGES_REQUEST";
export const SAVE_CHANGES_SUCCESS = "SAVE_CHANGES_SUCCESS";
export const SAVE_CHANGES_FAILURE = "SAVE_CHANGES_FAILURE";

export const FETCH_REGISTRIES_LAST_WEEKS_REQUEST =
  "FETCH_REGISTRIES_LAST_WEEKS_REQUEST";
export const FETCH_REGISTRIES_LAST_WEEKS_SUCCESS =
  "FETCH_REGISTRIES_LAST_WEEKS_SUCCESS";
export const FETCH_REGISTRIES_LAST_WEEKS_FAILURE =
  "FETCH_REGISTRIES_LAST_WEEKS_FAILURE";

export const FETCH_LATEST_REGISTRIES_REQUEST =
  "FETCH_LATEST_REGISTRIES_REQUEST";
export const FETCH_LATEST_REGISTRIES_SUCCESS =
  "FETCH_LATEST_REGISTRIES_SUCCESS";
export const FETCH_LATEST_REGISTRIES_FAILURE =
  "FETCH_LATEST_REGISTRIES_FAILURE";
