export const FETCH_REGISTRIES_BY_WEEK_REQUEST = "FETCH_TASK_BY_WEEK_REQUEST";
export const FETCH_REGISTRIES_BY_WEEK_SUCCESS = "FETCH_TASK_BY_WEEK_SUCCESS";
export const FETCH_REGISTRIES_BY_WEEK_FAILURE = "FETCH_TASK_BY_WEEK_FAILURE";

export const ADD_REGISTRY_TO_STORE = "ADD_REGISTRY_TO_STORE";

export const POST_REGISTRIES_REQUEST = "POST_REGISTRIES_REQUEST";
export const POST_REGISTRIES_SUCCESS = "POST_REGISTRIES_SUCCESS";
export const POST_REGISTRIES_FAILURE = "POST_REGISTRIES_FAILURE";
