export const ADD_REGISTRY_TO_STORE = "ADD_REGISTRY_TO_STORE";
export const REMOVE_NEW_REGISTRY_FROM_STORE = "REMOVE_NEW_REGISTRY_FROM_STORE";
export const REMOVE_REGISTRY_FROM_STORE = "REMOVE_REGISTRY_FROM_STORE";
export const UPDATE_REGISTRY_FROM_STORE = "UPDATE_REGISTRY_FROM_STORE";

export const FETCH_REGISTRIES_BY_WEEK_REQUEST = "FETCH_TASK_BY_WEEK_REQUEST";
export const FETCH_REGISTRIES_BY_WEEK_SUCCESS = "FETCH_TASK_BY_WEEK_SUCCESS";
export const FETCH_REGISTRIES_BY_WEEK_FAILURE = "FETCH_TASK_BY_WEEK_FAILURE";

export const SAVE_CHANGES_REQUEST = "SAVE_CHANGES_REQUEST";
export const SAVE_CHANGES_SUCCESS = "SAVE_CHANGES_SUCCESS";
export const SAVE_CHANGES_FAILURE = "SAVE_CHANGES_FAILURE";
