export const FETCH_TASK_STATS_REQUEST = "FETCH_TASK_STATS_REQUEST";
export const FETCH_TASK_STATS_SUCCESS = "FETCH_TASK_STATS_SUCCESS";
export const FETCH_TASK_STATS_FAILURE = "FETCH_TASK_STATS_FAILURE";
