// LOCAL TYPES

export const RESET_STATISTIC_DATA_STORE = "RESET_STATISTIC_DATA_STORE";

// API TYPES

export const FETCH_TASK_STATS_REQUEST = "FETCH_TASK_STATS_REQUEST";
export const FETCH_TASK_STATS_SUCCESS = "FETCH_TASK_STATS_SUCCESS";
export const FETCH_TASK_STATS_FAILURE = "FETCH_TASK_STATS_FAILURE";

export const FETCH_CUSTOMER_STATS_REQUEST = "FETCH_CUSTOMER_STATS_REQUEST";
export const FETCH_CUSTOMER_STATS_SUCCESS = "FETCH_CUSTOMER_STATS_SUCCESS";
export const FETCH_CUSTOMER_STATS_FAILURE = "FETCH_CUSTOMER_STATS_FAILURE";

export const FETCH_CUSTOMER_INTERNAL_STATS_REQUEST = "FETCH_CUSTOMER_INTERNAL_STATS_REQUEST";
export const FETCH_CUSTOMER_INTERNAL_STATS_SUCCESS = "FETCH_CUSTOMER_INTERNAL_STATS_SUCCESS";
export const FETCH_CUSTOMER_INTERNAL_STATS_FAILURE = "FETCH_CUSTOMER_INTERNAL_STATS_FAILURE";
