export const FETCH_TASK_BY_WEEK_REQUEST = "FETCH_TASK_BY_WEEK_REQUEST";
export const FETCH_TASK_BY_WEEK_SUCCESS = "FETCH_TASK_BY_WEEK_SUCCESS";
export const FETCH_TASK_BY_WEEK_FAILURE = "FETCH_TASK_BY_WEEK_FAILURE";